### ISSUE TITLE
Little website things

### ISSUE THREAD

**Issue by ghost** [tsubery/quantifier#3]
The logos of the services are broken for me:

<img width="1216" alt="screen shot 2016-08-31 at 18 00 45" src="https://cloud.githubusercontent.com/assets/423471/18136244/e0fd3d9c-6fa4-11e6-971b-52aa45f311cb.png">

And the link for beeminder sends you to "https://beemind.me/www.beeminder.com" which, of course, doesn't work. I thought I'd point that out. Thank you for your work.

**Comment by tsubery** [comment]
It is fixed now. Thank you for reporting the problem.
