### ISSUE TITLE
Topics tags under description. 

### ISSUE THREAD

**Issue by ran88dom99** [tsubery/quantifier#5]
https://github.com/topics/quantified-self
Your project is harder to find without 'topics'. Save researchers some trouble please.

**Comment by tsubery** [comment]
np, any particular topics you'd like to see there?

**Comment by ran88dom99** [comment]
Write the names of supported integrations in description so search find you. They all have tags but that may be going overboard.
habit-tracking  
time-management

**Comment by tsubery** [comment]
Thanks
